### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by Klaw807** [ls4154/leveldb-raw#1]
When I build this, it shows error:
"[ 82%] Linking CXX executable leveldbutil
/usr/bin/ld: cannot find -ldpdk: No such file or directory
/usr/bin/ld: cannot find -lrte_fib: No such file or directory
/usr/bin/ld: cannot find -lrte_mempool_bucket: No such file or directory
/usr/bin/ld: cannot find -lrte_rib: No such file or directory".
I wonder if it is because this version no longer fits well with the newest spdk and I wonder how can I fix this problem?

**Comment by ls4154** [comment]
It seems some of the dependencies are not installed or they might be no longer included in SPDK.
Unfortunately, I haven't used SPDK in years, so I don't know about the recent status.
Please check the link flags in CMakeLists and change it to work for your environment.

**Comment by Klaw807** [comment]
Thank you.
